In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [5]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [7]:
X_train.shape

(4457,)

In [8]:
X_test.shape

(1115,)

In [9]:
type(X_train)

pandas.core.series.Series

In [10]:
X_train[:4]

3001      Id onluy matters when getting on from offcampus
1192    Come to my home for one last time i wont do an...
2157    Hey cutie. How goes it? Here in WALES its kind...
3358    Brainless Baby Doll..:-D;-), vehicle sariyag d...
Name: Message, dtype: object

In [11]:
type(y_train)

pandas.core.series.Series

In [12]:
y_train[:4]

3001    0
1192    0
2157    0
3358    0
Name: spam, dtype: int64

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7702 sparse matrix of type '<class 'numpy.int64'>'
	with 59199 stored elements in Compressed Sparse Row format>

In [15]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
X_train_cv.shape

(4457, 7702)

In [27]:
v.get_feature_names_out()[1000:1055]

array(['apartment', 'apes', 'aphex', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'apology', 'app', 'apparently', 'appeal',
       'appendix', 'applausestore', 'applebees', 'apples', 'application',
       'apply', 'applying', 'appointment', 'appreciate', 'appreciated',
       'approaches', 'approaching', 'approx', 'apps', 'appt', 'appy',
       'april', 'aproach', 'apt', 'aptitude', 'aquarius', 'ar', 'arab',
       'arabian', 'arcade', 'ard', 'are', 'area', 'aren', 'arent',
       'arestaurant', 'aretaking', 'areyouunique', 'argentina', 'argh',
       'argue', 'arguing', 'argument', 'arguments', 'arise', 'arises',
       'arithmetic', 'arm'], dtype=object)

In [30]:
v.get_feature_names_out().shape

(7702,)

In [31]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [35]:
v.vocabulary_

{'id': 3591,
 'onluy': 4941,
 'matters': 4388,
 'when': 7448,
 'getting': 3133,
 'on': 4932,
 'from': 3030,
 'offcampus': 4892,
 'come': 1911,
 'to': 6907,
 'my': 4669,
 'home': 3480,
 'for': 2948,
 'one': 4936,
 'last': 4020,
 'time': 6874,
 'wont': 7543,
 'do': 2379,
 'anything': 992,
 'trust': 7030,
 'me': 4406,
 'hey': 3428,
 'cutie': 2147,
 'how': 3526,
 'goes': 3178,
 'it': 3760,
 'here': 3418,
 'in': 3643,
 'wales': 7334,
 'its': 3768,
 'kinda': 3941,
 'ok': 4914,
 'there': 6805,
 'is': 3749,
 'like': 4109,
 'hills': 3437,
 'and': 950,
 'shit': 6085,
 'but': 1578,
 'still': 6457,
 'avent': 1153,
 'killed': 3937,
 'myself': 4674,
 'brainless': 1478,
 'baby': 1183,
 'doll': 2406,
 'vehicle': 7240,
 'sariyag': 5894,
 'drive': 2462,
 'madoke': 4304,
 'barolla': 1227,
 'yunny': 7682,
 'goin': 3180,
 'be': 1266,
 'late': 4022,
 'okay': 4915,
 'no': 4791,
 'just': 3877,
 'shining': 6078,
 'that': 6785,
 'was': 7361,
 'meant': 4414,
 'signing': 6142,
 'sounds': 6317,
 'better': 1328,
 '

In [36]:
v.get_feature_names_out()[4488]

'mind'

In [37]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [38]:
X_train_np[:][0]

array([0, 0, 0, ..., 0, 0, 0])

In [49]:
np.where(X_train_np[55]!=0)

(array([ 745,  950, 1038, 1075, 1165, 2075, 2948, 3030, 3170, 3252, 3908,
        4406, 4838, 5769, 6231, 6234, 6788, 6819, 7441, 7479, 7539, 7558,
        7663, 7666]),)

In [53]:
X_train[:4][2157]

'Hey cutie. How goes it? Here in WALES its kinda ok. There is like hills and shit but i still avent killed myself.'

In [54]:
X_train_np[55][745]

1

In [55]:
v.get_feature_names_out()[745]

'about'

In [56]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv,y_train)


MultinomialNB()

In [57]:
X_test_cv = v.transform(X_test)

In [61]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

In [62]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       959
           1       0.95      0.92      0.94       156

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [63]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [65]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
     ('vectorizer', CountVectorizer()),
     ('nb', MultinomialNB())
 ])

In [66]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [67]:
clf.predict(emails)

array([0, 1])

In [69]:
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       959
           1       0.95      0.92      0.94       156

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

